# create /tmp/done directory to keep track of the installation
- name: Create /tmp/done directory if it does not exist
  ansible.builtin.file:
    path: /tmp/done
    state: directory
    mode: '0755'