---
- name: "Install MacOS Client | Create Velociraptor directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0750'
  with_items:
    - "{{ velociraptor_dir }}"
    - "{{ velociraptor_config_dir }}"

- name: "Install MacOS Client | Download velociraptor binary"
  ansible.builtin.get_url:
    url: "{{ velociraptor_url }}"
    dest: "{{ velociraptor_dir }}/velociraptor"
    owner: root
    group: root
    mode: '0750'

- name: "Install MacOS Client | Fetch velociraptor client config from server (.yaml)"
  ansible.builtin.slurp:
    src: /etc/velociraptor/client.config.yaml
  delegate_to: "{{ groups['velociraptor_server'][0] }}"
  become: yes
  register: client_config_content_yaml
  ignore_errors: yes

- name: "Install MacOS Client | Fetch velociraptor client config from server (.yml)"
  ansible.builtin.slurp:
    src: /etc/velociraptor/client.config.yml
  delegate_to: "{{ groups['velociraptor_server'][0] }}"
  become: yes
  register: client_config_content_yml
  when: client_config_content_yaml.failed | default(false)
  ignore_errors: yes

- name: "Install MacOS Client | Set client config content"
  ansible.builtin.set_fact:
    client_config_content: "{{ client_config_content_yml if (client_config_content_yaml.failed | default(false)) and not (client_config_content_yml.failed | default(true)) else client_config_content_yaml }}"
  failed_when: >
    (client_config_content_yaml.failed | default(false)) and
    (client_config_content_yml.failed | default(true) or client_config_content_yml is not defined)

- name: "Install MacOS Client | Copy velociraptor client config"
  ansible.builtin.copy:
    content: "{{ client_config_content.content | b64decode }}"
    dest: "{{ velociraptor_config_dir }}/client.config.yaml"
    owner: root
    group: root
    mode: '0640'
  notify:
    - Restart velociraptor nix client

- name: "Install MacOS Client | Install velociraptor systemd configuration"
  ansible.builtin.template:
    src: systemd-velociraptor-client.service.j2
    dest: /lib/systemd/system/velociraptor-client.service
    owner: root
    group: root
    mode: '0644'
  register: systemd
  notify:
    - Reload velociraptor-client

- name: "Install MacOS Client | Enable and start velociraptor-client systemd service"
  ansible.builtin.service:
    name: velociraptor-client
    enabled: true
    state: 'started'
