---
- name: Get 3 octets and append .52
  win_shell: |
    $ip = (Get-NetIPConfiguration | Where-Object { $_.IPv4DefaultGateway -ne $null } | Select-Object -ExpandProperty IPv4Address).IPv4Address
    if ($ip) {
      ($ip.Split('.')[0..2] -join '.') + '.52:8000'
    }
  register: client_ip_port

- name: "Windows Client | Create directory"
  ansible.windows.win_file:
    path: "{{ _velociraptor_windows_dir }}"
    state: directory

- name: "Windows Client | Get velociraptor msi"
  ansible.windows.win_get_url:
    url: "{{ velociraptor_url }}"
    dest: "{{ _velociraptor_windows_dir }}{{ velociraptor_msi }}"

- name: "Windows Client | Install velociraptor msi"
  ansible.windows.win_package:
    path: "{{ _velociraptor_windows_dir }}{{ velociraptor_msi }}"
    state: present

- name: "Windows Client | Copy velociraptor client config"
  ansible.builtin.template:
    src: client.config.yaml.j2
    dest: "{{ _velociraptor_windows_dir }}client.config.yaml"
  notify:
    - Restart velociraptor windows client
