---
- name: Add Edge bookmark to bookmarks bar for Kibana
  block: 
  - name: Add Edge bookmark to bookmarks bar
    ansible.windows.win_template:
      src: edge_bookmark.json.j2
      dest: 'C:\Users\{{ ansible_user }}\AppData\Local\Microsoft\Edge\User Data\Default\Bookmarks'
    vars:
      bookmark_name: "ELK"
      bookmark_url: "http://:5601"